#!/usr/bin/env bash

# Quick Start Guide - PBIX Upload Feature

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   PBIX UPLOAD - QUICK START                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "✨ NEW FEATURE: Upload Power BI Models (PBIX/PBIT)"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "WHAT YOU CAN NOW DO:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. 📊 UPLOAD YOUR PBIX/PBIT FILES"
echo "   └─ Extract tables, columns, relationships, measures automatically"
echo ""
echo "2. 🤖 TRAIN AGENT ON YOUR MODEL"
echo "   └─ Agent learns about YOUR specific schema"
echo ""
echo "3. 💬 GENERATE ACCURATE CODE"
echo "   └─ Code references YOUR actual table names"
echo ""
echo "4. 🔄 KEEP CSV FUNCTIONALITY"
echo "   └─ Still upload CSVs for additional data"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "STEP-BY-STEP USAGE:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "STEP 1: Start the Application"
echo "  $ cd /home/gopal-upadhyay/AI_Bot_MAQ"
echo "  $ python run_ui.py"
echo "  └─ Opens at http://localhost:8501"
echo ""

echo "STEP 2: Create a New Model"
echo "  • Click '+ New Model' button"
echo "  • Give it a name (e.g., 'SalesAnalytics')"
echo "  • Click 'Create'"
echo ""

echo "STEP 3: Upload Your PBIX"
echo "  • You'll see: '📊 Step 1: Upload Power BI Model (PBIX/PBIT)'"
echo "  • Click 'Select a PBIX or PBIT file'"
echo "  • Choose your Power BI model file"
echo "  • Click '🔍 Extract & Train from PBIX Model'"
echo ""

echo "STEP 4: Wait for Extraction"
echo "  • System extracts:"
echo "    ✓ Tables (names, columns, types)"
echo "    ✓ Relationships (joins)"
echo "    ✓ Measures (DAX expressions)"
echo ""

echo "STEP 5: See Results"
echo "  • Displays metrics:"
echo "    • Tables Found: X"
echo "    • Relationships: X"
echo "    • Measures: X"
echo "  • Shows extracted schema"
echo "  • Shows relationships"
echo "  • Shows measures (first 10)"
echo ""

echo "STEP 6: Generate Code"
echo "  • Go to 'Generate New Item' tab"
echo "  • Ask anything about your model:"
echo "    'Create total sales measure'"
echo "    'Generate PySpark code for Sales'"
echo "    'Write DAX for month-over-month growth'"
echo "  • Agent now knows YOUR table/column names!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "BEFORE vs AFTER COMPARISON:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "BEFORE (Manual CSV Upload):"
echo "  1. Manually describe table structure"
echo "  2. Upload CSVs"
echo "  3. Agent may not know exact column names"
echo "  4. Generated code might not match your model"
echo ""

echo "AFTER (PBIX Upload):"
echo "  1. Upload PBIX file (1 click)"
echo "  2. System extracts everything automatically"
echo "  3. Agent knows EXACT table/column names"
echo "  4. Generated code perfectly matches your model"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "SUPPORTED FORMATS:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  ✅ .pbix (Power BI Desktop files)"
echo "  ✅ .pbit (Power BI Template files)"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "FEATURES YOU CAN NOW USE:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "EXTRACTION:"
echo "  ✅ Tables & columns auto-detected"
echo "  ✅ Relationships auto-detected"
echo "  ✅ Measures extracted"
echo "  ✅ Data types preserved"
echo ""

echo "DISPLAY:"
echo "  ✅ See extracted tables & columns"
echo "  ✅ See detected relationships"
echo "  ✅ See extracted measures"
echo "  ✅ File info (size, model type)"
echo ""

echo "AGENT TRAINING:"
echo "  ✅ Automatic agent retraining"
echo "  ✅ Learns from your model schema"
echo "  ✅ Generates accurate code"
echo ""

echo "COMPATIBILITY:"
echo "  ✅ Works with Step 2 (CSV upload)"
echo "  ✅ Keeps all existing features"
echo "  ✅ No changes to CSV workflow"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "EXAMPLE USAGE:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "You have: SalesAnalytics.pbix with tables:"
echo "  • Sales (OrderID, Amount, Date, ProductID)"
echo "  • Product (ProductID, Name, Category)"
echo "  • SalesPerson (EmployeeID, Name, Region)"
echo ""

echo "After upload:"
echo "  ✓ System extracts all 3 tables"
echo "  ✓ Detects relationships between them"
echo "  ✓ Extracts any existing measures"
echo ""

echo "Then you ask:"
echo "  'Create a measure for total revenue by region'"
echo ""

echo "Agent generates:"
echo "  Revenue_by_Region = CALCULATE("
echo "    SUM(Sales[Amount]),"
echo "    ALLEXCEPT(SalesPerson, SalesPerson[Region])"
echo "  )"
echo ""

echo "✅ Perfect because agent knows YOUR exact table names!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "FILE LOCATION & DOCUMENTATION:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "Main Guide:"
echo "  📄 /home/gopal-upadhyay/AI_Bot_MAQ/PBIX_UPLOAD_GUIDE.md"
echo ""

echo "Implementation Files:"
echo "  🔧 /home/gopal-upadhyay/AI_Bot_MAQ/assistant_app/pbix_extractor.py"
echo "  🔧 /home/gopal-upadhyay/AI_Bot_MAQ/assistant_app/ui.py"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TROUBLESHOOTING:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "❌ Error: 'No valid Power BI model found'"
echo "   ✅ Solution: Make sure it's a real PBIX, not a copy"
echo ""

echo "❌ Error: 'Not a valid ZIP file'"
echo "   ✅ Solution: File might be corrupted, try downloading again"
echo ""

echo "❌ Error: '0 tables found'"
echo "   ✅ Solution: Model might be empty, check in Power BI"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "READY TO START?"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "1. Open your Power BI model file (.pbix)"
echo "2. Start the application:"
echo "   $ python /home/gopal-upadhyay/AI_Bot_MAQ/run_ui.py"
echo "3. Create a new model"
echo "4. Upload your PBIX file"
echo "5. Extract & train"
echo "6. Start generating code!"
echo ""

echo "🚀 Happy modeling!"
echo ""
